const SUBMIT_ACCOUNT_FORM = 'SUBMIT_ACCOUNT_FORM';
const PERSIST_STRIPE_TOKEN = 'PERSIST_STRIPE_TOKEN';
const DELETE_STRIPE_TOKEN = 'DELETE_STRIPE_TOKEN';
const USERS_RECEIVED = 'USERS_RECEIVED';
const USERS_REQUESTED = 'USERS_REQUESTED';
const USER_REQUEST_FAILED = 'USER_REQUEST_FAILED';
const GET_USER_DATA = 'GET_USER_DATA';
const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
const USER_DATA_RECEIVED = 'USER_DATA_RECEIVED';
const USER_DATA_UPDATED = 'USER_DATA_UPDATED';
const PASSWORD_UPDATED = 'PASSWORD_UPDATED';
const USER_DATA_FAILED = 'USER_DATA_FAILED';
const CLEAR_USER_DATA = 'CLEAR_USER_DATA';
export default {
  SUBMIT_ACCOUNT_FORM,
  PERSIST_STRIPE_TOKEN,
  DELETE_STRIPE_TOKEN,
  USERS_RECEIVED,
  USERS_REQUESTED,
  USER_REQUEST_FAILED,
  GET_USER_DATA,
  USER_DATA_RECEIVED,
  UPDATE_USER_DATA,
  UPDATE_PASSWORD,
  USER_DATA_UPDATED,
  PASSWORD_UPDATED,
  USER_DATA_FAILED,
  CLEAR_USER_DATA
};
