export default {
  UPDATE_FIELD: 'UPDATE_FIELD',
  AUTHENTICATED: 'AUTHENTICATED',
  AUTHENTICATION_FAILURE: 'AUTHENTICATION_FAILURE',
  SIGNIN_ATTEMPT: 'SIGNIN_ATTEMPT',
  SIGNUP_ATTEMPT: 'SIGNUP_ATTEMPT',
  UNAUTHENTICATED: 'UNAUTHENTICATED'
};
